- apps/web/src/components/hero/index.tsx
Fixes:
```
web:dev: Image with src "/media/landari-laskiaisrieha.jpg" has legacy prop "layout". Did you forget to run the codemod?
web:dev: Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
web:dev: Image with src "/media/landari-laskiaisrieha.jpg" has legacy prop "objectFit". Did you forget to run the codemod?
web:dev: Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
web:dev: Image with src "/media/landari-laskiaisrieha.jpg" has legacy prop "objectPosition". Did you forget to run the codemod?
web:dev: Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
web:dev: Image with src "/media/landari-otatarhanajot.jpg" has legacy prop "layout". Did you forget to run the codemod?
web:dev: Read more: …
```
> fix legacy image props

- apps/cms/src/collections/pages.ts
- apps/cms/src/preview.ts
- apps/web/src/app/[lang]/layout.tsx
- apps/web/src/components/admin-bar-client.tsx
- apps/web/src/components/footer/index.tsx
- apps/web/src/components/main-nav/link-list.tsx
- apps/web/src/components/mobile-nav/link-list.tsx
- apps/web/src/lib/api/fetcher.ts
- apps/web/src/lib/utils.ts
- changes `path` to be of format `[lang]/[topic]/[slug]` instead of just `[topic]/[slug]` in backend API call. This was anyways reformatted to this in frontend, and this change enabled easier non-hacky way of doing preview URLs so seems like a good change
- preview should work with both locales, and `exit Preview`-button should work now too.
- Added red banner on top of site indicating draft Mode
> preview fixes and localization support

- apps/web/package.json
- package.json
- pnpm-lock.yaml
Turbopack is now stable enough to be used in dev for Next.js. Speeds up development server big time
> use turbopack in dev

- apps/web/src/components/mobile-nav/index.tsx
- apps/web/src/components/mobile-nav/link-list.tsx
Due to `vh` units being absolute shit, they don't handle things like address bars properly. There's `dvh` unit available, but from my experience it's just better to have a flex container with 100% height. See images below for before/after when scrolling to the absolute bottom of navigation bar.
Before:
After:
> Fix issue with mobile navigation cutting off from the bottom

- apps/cms/package.json
- apps/cms/src/collections/pages.ts
- apps/cms/src/util/index.ts
- pnpm-lock.yaml
Better than blocking creating altogether, append a short nanoid to the end
Closes #294
> append random slug to page path if duplicate, make paths unique

- apps/cms/package.json
- apps/cms/src/payload.config.ts
- apps/cms/src/payload.d.ts
- apps/cms/src/util/import.ts
- apps/cms/tsconfig.json
- apps/cms/tsconfig.server.json
- apps/web/package.json
- packages/config-typescript/nextjs.json
- packages/config-typescript/react-app.json
- packages/config-typescript/react-library.json
- packages/ui/package.json
- pnpm-lock.yaml
Title. At the same time bumped client targets to `ES2018` and cms to `ES2023`, `ES2018` was necessary to prevent typescript errors.
Attempt number 2, with better typescript configurations for CMS
> Chore: bump typescript to 5.5.2

- apps/cms/src/collections/committees/committee-members.ts
- apps/cms/src/collections/weekly-newsletters/news-items.ts
- apps/cms/src/migrations/20240616_101649_Add_displayTitle_to_database.ts
- data/gen/db/board-members.json
- data/gen/db/boards.json
- data/gen/db/committee-members.json
- data/gen/db/committees.json
- data/gen/db/documents.json
- data/gen/db/globals.json
- data/gen/db/magazine-issues.json
- data/gen/db/magazines.json
- data/gen/db/media.json
- data/gen/db/news.json
- data/gen/db/pages.json
- data/gen/db/topics.json
When merging this, make sure to run the migration from the command line into prod!
> fix: searching issues in payload

- apps/web/src/components/magazine-list/index.tsx
Currently there are sometimes unnecessary space if there are some covers of Alkorytmi that have weird aspect ratio:
This PR makes it look like this:
> fix: covers of alkorytmi with different aspect ratio

- apps/web/src/app/[locale]/[...path]/page.tsx
- apps/web/src/app/[locale]/error.tsx
- apps/web/src/app/[locale]/global-error.tsx
- apps/web/src/app/[locale]/not-found.tsx
- apps/web/src/app/[locale]/signups/not-found.tsx
- apps/web/src/app/[locale]/tapahtumat/not-found.tsx
- apps/web/src/lib/api/external/ilmomasiina/index.ts
- apps/web/src/locales/en.ts
- apps/web/src/locales/fi.ts
- feat: add granular not-found pages to events and signups
- fix: add some padding to page headers
Closes #443
> Signup not found page

- apps/web/src/app/[locale]/globals.css
- apps/web/src/app/[locale]/signups/[signupId]/[signupEditToken]/signup-form.tsx
- apps/web/src/locales/en.ts
- apps/web/src/locales/fi.ts
- feat: add confirm popover to sign up deletion
Closes #444
> feat: add confirm popover to sign up deletion

- apps/web/src/lib/ics.ts
In event ICS file, end time was wrong. Fixed issue by marking also end time as UTC.
Closes #455
> fix: mark event end time as UTC in ICS file

- apps/web/src/components/main-nav/language-selector.tsx
- apps/web/src/components/mobile-nav/language-selector.tsx
Prefetching language selector links causes the language cookie to change (which in turn causes the locale-less url `tietokilta.fi` to open always on different language), so disabled prefetching for them. 
Closes #486
> fix: Prevent accidental language changes caused by prefetching

- apps/web/src/app/[locale]/signups/[signupId]/[signupEditToken]/signup-form.tsx
- apps/web/src/locales/en.ts
- apps/web/src/locales/fi.ts
- fix: disable sign up editing and deletion if event sign ups are closed
> fix: disable sign up editing and deletion if event sign ups are closed

- apps/cms/src/collections/weekly-newsletters/newsletter-button.tsx
- apps/cms/src/collections/weekly-newsletters/weekly-newsletters.ts
- apps/cms/src/controllers/newsletter-controller.ts
- apps/cms/src/emails/helper-components.tsx
- apps/cms/src/emails/newsletter-email.tsx
- apps/cms/src/emails/newsletter.tsx
Few improvements to newsletter email. Adds numbering to newsletter category headers and includes fonts for those email providers that supports it. Here should be the list of supported email providers. https://www.caniemail.com/features/css-at-font-face/
- ...
> Fix: Newsletter numbering

- apps/web/src/lib/ics.ts
- fix: force ics cache busting by setting dtstamp as current time
> fix: force ics cache busting by setting dtstamp as current time

- apps/web/src/app/[locale]/signups/[signupId]/[signupEditToken]/signup-form.tsx
When clicking "Sign up" on event page, the scroll position didn't change (problem with phones, since the signup page was then scrolled to footer). Now the Sign up form always scrolls the page to top when rendered for the first time.
Handles the same issue as #458 so if this gets merged, that should probably be closed.
Closes #457.
> feat: Scroll to top when opening signup page

- apps/web/package.json
- apps/web/src/app/[locale]/events/[slug]/page.tsx
- apps/web/src/app/[locale]/signups/[signupId]/[signupEditToken]/page.tsx
- apps/web/src/app/[locale]/signups/[signupId]/[signupEditToken]/signup-form.tsx
- apps/web/src/components/events-display/index.tsx
- apps/web/src/custom-pages/event-calendar.tsx
- apps/web/src/custom-pages/events-page.tsx
- apps/web/src/lib/plugins/remark-i18n.ts
- apps/web/src/lib/utils.ts
- pnpm-lock.yaml
- feat: implement support for localizing event titles in UI with common practice divider
- feat: implement support for custom localization in markdown content
This is done with a custom markdown `Definition` block.
Example:
```markdown
Default language content
[lang]: # (en)
English content
```
Will be transformed depending on the locale option to either:
```markdown
Default language content
```
or:
```markdown
English content
```
Without the custom plugin, such as in `ilmo.tietokilta.fi` the definition won't be rendered at all and will function like a comment. You may still add the traditional divider with `---` after each language definition and it will look nice on both versions.
- closes #484
> feat: support markdown localization in ilmomasiina UI

- apps/web/src/components/invoice-generator/index.tsx
- apps/web/src/locales/en.ts
- apps/web/src/locales/fi.ts
Adds an automatically calculated sum for each individual item in an invoice
> feat: add total price to invoice generator

- apps/web/src/components/invoice-generator/index.tsx
> fix laskugen props

- apps/web/src/components/committee-card/index.tsx
- fix: committee members grid layout on chrome browsers after update
- fix: add accessible link text to committee member email+tg links
- fix: invalid dom nesting with committee member email+tg links
> fix: committee members grid layout on chrome browsers after update

- .devcontainer.json
- .envrc
- .gitignore
- flake.lock
- flake.nix
- package.json
- pnpm-lock.yaml
- add nix flake and .devcontainer.json to make setting up the development environment trivial
> feat: add nix flake and .devcontainer.json

- apps/web/src/components/digi-committee-recruitment-alert.tsx
- **chore: update recruitment alert to match the committee 2025**
- ...
> chore: update recruitment alert

- apps/web/src/app/[locale]/(infoscreen)/infoscreen/layout.tsx
- apps/web/src/app/[locale]/(infoscreen)/infoscreen/page.tsx
- apps/web/src/app/[locale]/(main)/[...path]/page.tsx
- apps/web/src/app/[locale]/(main)/error.tsx
- apps/web/src/app/[locale]/(main)/events/[slug]/page.tsx
- apps/web/src/app/[locale]/(main)/events/[slug]/signup-button.tsx
- apps/web/src/app/[locale]/(main)/global-error.tsx
- apps/web/src/app/[locale]/(main)/layout.tsx
- apps/web/src/app/[locale]/(main)/not-found.tsx
- apps/web/src/app/[locale]/(main)/page.tsx
- apps/web/src/app/[locale]/(main)/signups/[signupId]/[signupEditToken]/page.tsx
- apps/web/src/app/[locale]/(main)/signups/[signupId]/[signupEditToken]/signup-form.tsx
- apps/web/src/app/[locale]/(main)/signups/not-found.tsx
- apps/web/src/app/[locale]/(main)/tapahtumat/not-found.tsx
- apps/web/src/app/[locale]/(main)/weekly-newsletters/[slug]/page.tsx
- apps/web/tsconfig.json
- Added shorthands `@components`, `@lib`, `@locales` and `@custom-pages` to allow shorter paths
Closes #603
> feat: Add tsconfig shortcut paths for components etc for web

- apps/cms/src/blocks/partners.ts
- apps/cms/src/collections/partners.ts
- apps/cms/src/payload.config.ts
- apps/web/src/components/image-link-grid/index.tsx
- apps/web/src/components/lexical/lexical-serializer.tsx
- apps/web/src/components/partner-logos/index.tsx
- apps/web/src/lib/api/partners.ts
- packages/cms-types/lexical.ts
- packages/cms-types/payload.ts
- packages/cms-types/schema.gql
- Partners are now a separtate collection on CMS
- Partner grid is now a block that can be added to pages
- Partner grid is sorted alphabetically and allows selecting logo size (small, medium, large)
When this is merged, we can create partners on the CMS. Then the grids on [sponsors page](https://tietokilta.fi/fi/yritykset) can be migrated to use new blocks that update automatically.
> feat: Add new component for displaying partners

- apps/cms/src/collections/media.ts
The Lexical Serializer code currently expects that the files are images, and we anyways
don't want to support hosting videos directly, but instead use external services (e.g. YouTube) for video hosting.
> fix: restrict media to only image mime types

- apps/cms/src/collections/committees/committees.ts
- apps/cms/src/util/import.ts
- apps/web/src/components/committee-list/index.tsx
- apps/web/src/lib/api/committees.ts
- packages/cms-types/payload.ts
- packages/cms-types/schema.gql
The equality page needs a committee component that shouldn't be visible in the actual committee list. This adds a checkbox in the CMS to hide a committee from the committee list pages.
- [✔️] telegram conversation 👍 
- [✔️] Prefix your PR title with feat:, fix:, chore:, or docs:.
- [✔️] This message body should clearly illustrate what problems it solves.
- [✔️] Make sure the commit history is linear, up-to-date with main branch and does not contain any erroneous changes
- [✔️] Format code with `pnpm format` and lint the project with `pnpm lint`
> feat: Add committee hiding option

- apps/web/src/components/invoice-generator/index.tsx
Closes https://github.com/Tietokilta/web/issues/607
Testing checklist:
> fix: dont reset invoice generator form on failed submission

- apps/web/src/components/infoscreen/kanttiinit/index.tsx
- Allergy information on infoscreen was too wide, and caused scrollbar to appear on infoscreen. This is now fixed
> fix: Infoscreen allergy information overflow

- apps/cms/src/blocks/highlight-card.ts
- apps/cms/src/payload.config.ts
- apps/web/src/components/highlight-card/index.tsx
- apps/web/src/components/lexical/lexical-serializer.tsx
- packages/cms-types/lexical.ts
Fixes #485 
Adds a rich-text highlight card block into CMS and web
> feat: add highlight card block with rich-text

- apps/web/src/app/[locale]/(main)/events/[slug]/opengraph-image.tsx
- Fixes #689 by removing markdown syntax from the event preview OpenGraph image.
> fix: strip markdown syntax from event preview image

- .github/workflows/build.yml
- chore: enable ci for pull requests from forks with concurrency control
- Noticed in #745
> chore: enable ci for PRs from forks with concurrency control

- apps/web/next-env.d.ts
- apps/web/src/components/invoice-generator/index.tsx
- Added client-side validation to enforce a maximum payload size of **24MB** in `invoice-generator.tsx`.
- Before form submission, the total size of file attachments and text inputs is calculated.
- If the payload exceeds 24MB:
- Submission is blocked.
- A friendly toast error message is displayed.
- Prevents backend from returning `413 Payload Too Large` errors.
**Related Issue**
Closes #744
> feat(invoice-generator): enforce 24MB client-side payload size limit
