.env.example, apps/cms/package.json, apps/cms/src/payload.config.ts, apps/cms/tsconfig.json, apps/web/src/middleware.ts, packages/cms-types/payload.ts, packages/cms-types/schema.gql, packages/cms/src/plugins/oauth/OAuthButton.tsx, packages/cms/src/plugins/oauth/index.ts, packages/cms/src/plugins/oauth/oAuthClient.ts, packages/cms/src/plugins/oauth/oAuthServer.ts, packages/cms/src/plugins/oauth/types.ts, pnpm-lock.yaml
Now members of The google workspace account can sign in with SSO to the Admin panel. Perhaps some access control would be required at some point but this is good for now
Closes #43
=> Add Google OAuth SSO

apps/cms/src/collections/pages.ts, apps/cms/src/hooks/revalidate-page.ts, apps/cms/src/util.ts, apps/web/src/app/[lang]/[...path]/page.tsx, apps/web/src/components/main-nav/index.tsx, apps/web/src/components/main-nav/language-selector.tsx, apps/web/src/components/main-nav/logo-link.tsx, apps/web/src/components/mobile-nav/index.tsx, apps/web/src/components/mobile-nav/language-selector.tsx, apps/web/src/components/mobile-nav/link-list.tsx, apps/web/src/components/mobile-nav/logo-link.tsx, apps/web/src/lib/api/fetcher.ts
=> add language selector

apps/cms/src/collections/weekly-newsletters/news-items.ts, apps/cms/src/collections/weekly-newsletters/weekly-newsletters.ts, apps/cms/src/fields/news-item-category.ts, apps/cms/src/payload.config.ts, packages/cms-types/payload.ts, packages/cms-types/schema.gql
=> add weekly mails collections

apps/cms/src/collections/pages.ts, apps/cms/src/hooks/revalidate-page.ts, apps/web/src/app/[locale]/[...path]/page.tsx, apps/web/src/lib/api/fetcher.ts, apps/web/src/lib/api/pages.ts, data/gen/db/_pages_versions.json, data/gen/db/pages.json, pnpm-lock.yaml
=> fix page queries only querying by slug, query by path

apps/cms/src/collections/board/board-members.ts, apps/web/src/components/board-grid/index.tsx, packages/cms-types/payload.ts, packages/cms-types/schema.gql, packages/ui/lib/icons/index.tsx
Add possibility to put a phone number for a board member
=> Phonenumber for board member

.env.example, Dockerfile, apps/web/src/components/footer/index.tsx, apps/web/src/components/footer/version-sha.tsx, turbo.json
Adds a copyright notice and a version SHA linking to the actual commit
=> add copyright + version SHA to footer

apps/web/src/components/lexical/lexical-serializer.tsx
=> Add links to headings

apps/web/src/components/announcement-card/index.tsx
=> move announcement card chevron to right

apps/web/src/app/[locale]/[...path]/page.tsx, apps/web/src/app/[locale]/events/[slug]/page.tsx, apps/web/src/app/[locale]/global-error.tsx, apps/web/src/app/[locale]/layout.tsx, apps/web/src/app/[locale]/not-found.tsx, apps/web/src/app/[locale]/page.tsx, apps/web/src/components/skip-link/index.tsx, apps/web/src/custom-pages/events-page.tsx, apps/web/src/custom-pages/weekly-newsletter-page.tsx, apps/web/src/custom-pages/weekly-newsletters-list-page.tsx, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts
=> add skip to main content button

apps/web/src/app/[locale]/events/[slug]/page.tsx, apps/web/src/components/announcement-card/index.tsx, apps/web/src/components/events-display/index.tsx, apps/web/src/components/footer/index.tsx, apps/web/src/components/footer/version-sha.tsx, apps/web/src/components/main-nav/language-selector.tsx, apps/web/src/components/mobile-nav/language-selector.tsx, apps/web/src/components/mobile-nav/link-list.tsx, apps/web/src/components/table-of-contents/index.tsx, apps/web/src/custom-pages/events-page.tsx, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts, apps/web/tailwind.config.js, packages/ui/lib/components/button/index.tsx
=> improve link text on screen readers

apps/web/src/components/committee-card/index.tsx
Improve name formatting to better support for long names.
=> improve name formatting

apps/cms/src/blocks/google-form.ts, apps/cms/src/payload.config.ts, apps/web/src/components/google-form/index.tsx, apps/web/src/components/lexical/lexical-serializer.tsx, packages/cms-types/lexical.ts
=> add Google Forms block

apps/web/src/components/committee-card/index.tsx, apps/web/src/components/magazine-list/index.tsx
Improve Alkorytmi display and committee member listing
=> improve Alkorytmi display

apps/cms/src/blocks/editor-in-chief.ts, apps/cms/src/payload.config.ts, apps/web/package.json, apps/web/src/components/editor-in-chief/index.tsx, apps/web/src/components/lexical/lexical-serializer.tsx, packages/cms-types/lexical.ts, pnpm-lock.yaml
Add editor-in-chief block with a dvd effect.
=> add editor-in-chief block

apps/cms/src/collections/committees/committee-members.ts, packages/cms-types/payload.ts, packages/cms-types/schema.gql
- add a displayTitle to admin panel for committee members that includes name and title
- makes it easier to search and select the right member when adding new members
=> feat: add role title to committee members display title

apps/cms/src/collections/magazines/magazine-issues.ts, apps/web/src/components/magazine-list/index.tsx, packages/cms-types/payload.ts, packages/cms-types/schema.gql
- Adds possibility for issue number of magazine issue to be text instead of number. This is very important feature for Rytmiryhmä :eyes:
- Improves display of Alkorytmi issues:
- There are maximum of four issues per row. If for some weird reason there would be over four issues of Alkorytmi published some year, it would not make all boxes 4+ issues wide.
- The box is no longer too big on some screen sizes.
=> feat: Alkorytmi improvements

LICENSE
- MIT license project so anyone  can freely use it as a base for their own website or project
=> mit license project

apps/cms/package.json, apps/cms/src/blocks/image-link-grid.ts, apps/cms/src/collections/documents.ts, apps/web/package.json, package.json, packages/config-eslint/package.json, packages/ui/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
- chore: update deps
- feat(admin): enable upload previews for upload fields
=> chore: update deps

apps/web/package.json, apps/web/src/app/[locale]/layout.tsx, pnpm-lock.yaml
- feat: add next toploader for a loading indicator on page navigate
=> feat: add next toploader for a loading indicator on page navigate

apps/web/src/app/[locale]/[...path]/page.tsx, apps/web/src/app/[locale]/error.tsx, apps/web/src/app/[locale]/events/[slug]/page.tsx, apps/web/src/app/[locale]/global-error.tsx, apps/web/src/app/[locale]/not-found.tsx, apps/web/src/components/mobile-nav/index.tsx, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts, packages/ui/lib/components/card/index.tsx, packages/ui/lib/components/index.tsx, packages/ui/lib/components/sheet/index.tsx
- feat(ui): extract common pattern to card component
- fix: mobile sheet nav accessibility issues
=> feat(ui): refactor cards to component

apps/cms/package.json, apps/cms/src/collections/committees/committee-members.ts, apps/cms/src/collections/committees/committees.ts, apps/cms/src/collections/media.ts, apps/cms/src/controllers/committees-import-controller.ts, apps/cms/src/controllers/link-committee-photos.ts, apps/cms/src/controllers/media-import-controller.ts, apps/cms/src/views/actions-view.tsx, data/gen/db/committee-members.json, data/gen/db/committees.json, data/gen/db/documents.json, data/gen/db/news-items.json, data/gen/db/pages.json, data/gen/db/payload-migrations.json, pnpm-lock.yaml, scripts/upload_file.sh
=> Add endpoint for uploading media

apps/web/src/components/committee-list/index.tsx, data/gen/db/committees.json
- ...
https://github.com/Tietokilta/web/issues/445
- [ X] Prefix your PR title with feat:, fix:, chore:, or docs:.
- [ X] Make sure the commit history is linear, up-to-date with main branch and does not contain any erroneous changes
=> fix:Change committee list order

apps/web/src/app/[locale]/layout.tsx, apps/web/src/components/digi-committee-recruitment-alert.tsx
- feat: add recruitment text to dev console on page load
Closes #437
=> feat: add recruitment text to dev console on page load

apps/cms/src/collections/weekly-newsletters/news-items.ts, apps/web/src/custom-pages/weekly-newsletter-page.tsx, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts, packages/cms-types/payload.ts, packages/cms-types/schema.gql
Add link field to newsletter events that renders a link to a sign up page at a specified URL
Closes #314
=> feat: link newsletter events to ilmomasiina

apps/cms/src/access/published-or-signed-in.ts, apps/cms/src/collections/weekly-newsletters/weekly-newsletters.ts, packages/cms-types/payload.ts, packages/cms-types/schema.gql, pnpm-lock.yaml
=> Feat: Add possibility to create drafts for weekly newsletters

apps/web/src/app/[locale]/events/[slug]/page.tsx, apps/web/src/app/[locale]/events/[slug]/signup-button.tsx
- fix: disable sign up button while form is submitting
=> fix: disable sign up button while form is submitting

apps/web/src/components/committee-card/index.tsx
- fix: consistent height for committee member photos and placeholders
=> fix: consistent height for committee member photos and placeholders

apps/web/src/app/[locale]/events/[slug]/page.tsx, packages/ui/lib/components/button/index.tsx
- fix: hide repetitive "sign up" text from multi quota events
- fix: balance multi-row text on button styles
=> feat: remove repetitive sign up text from multi quota events

apps/cms/src/collections/weekly-newsletters/newsletter-button.tsx, apps/cms/src/controllers/newsletter-controller.ts
Some browsers or devices have limited clipboard size. This makes sure that whole html is downloaded.
- ...
=> Fix: Change button to download HTML instead of copying

apps/web/src/components/invoice-generator/index.tsx
Title. Each item had the title "product", which was inaccurate so it was changed to "attachment."
=> fix: changed lasku generaattori items title

apps/web/src/app/[locale]/signups/[signupId]/[signupEditToken]/signup-form.tsx, apps/web/src/lib/api/external/helpers.ts, apps/web/src/lib/api/external/ilmomasiina/actions.ts, apps/web/src/lib/api/external/ilmomasiina/index.ts, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts
- feat: render per-field errors from ilmomasiina in frontend
- fix: properly map multiple choice questions to array in ilmomasiina integration
=> feat: render per-field errors in ilmomasiina integration, fix multiple choice

apps/cms/src/collections/news.ts, apps/web/src/components/announcement-card/index.tsx, packages/cms-types/payload.ts, packages/cms-types/schema.gql
- feat: add external link ctaType to news
=> feat: add external link ctaType to news

apps/web/src/app/[locale]/events/[slug]/page.tsx, apps/web/src/app/[locale]/signups/[signupId]/[signupEditToken]/page.tsx, apps/web/src/custom-pages/events-page.tsx, apps/web/src/lib/api/external/ilmomasiina/index.ts, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts
- feat: support infinite quota in UI
=> feat: support infinite quota in UI

apps/cms/src/collections/committees/committee-members.ts, apps/web/src/components/committee-card/index.tsx, data/gen/db/committee-members.json, packages/cms-types/payload.ts, packages/cms-types/schema.gql
- ...
https://github.com/Tietokilta/web/issues/439
Added also telegram as that field was already in the schema. After merge, I will add the emails for committee chairs.
=> Feat: Add email field for committee members

apps/cms/src/collections/pages.ts, apps/web/src/app/[locale]/[...path]/page.tsx, apps/web/src/components/event-card/index.tsx, apps/web/src/custom-pages/all-events-page.tsx, apps/web/src/custom-pages/events-page.tsx, apps/web/src/lib/api/external/ilmomasiina/index.ts, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts, packages/cms-types/payload.ts, packages/cms-types/schema.gql
Closes [#487](https://github.com/Tietokilta/web/issues/487)
- ...
=> Create all events page

apps/web/src/custom-pages/all-events-page.tsx, apps/web/src/lib/api/external/ilmomasiina/index.ts
Updates ilmomasiina integration to be compatible with https://github.com/Tietokilta/ilmomasiina/pull/154
=> feat: update events fetch for ilmomasiina 2.0.0-alpha37

.env.example, .github/workflows/build.yml, apps/cms/package.json, package.json, packages/config-eslint/package.json, packages/ui/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: update dependencies

.devcontainer.json
=> fix: set eslint.runtime to node

apps/web/src/app/[locale]/(main)/events/[slug]/page.tsx, apps/web/src/app/[locale]/(main)/signups/[signupId]/[signupEditToken]/page.tsx
- feat: don't index event and signup pages
=> feat: don't index event and signup pages

apps/web/package.json, apps/web/src/app/[locale]/(main)/layout.tsx, apps/web/src/components/invoice-generator/index.tsx, pnpm-lock.yaml
Closes https://github.com/Tietokilta/web/issues/482
- ...
- [X ] If your PR is related to a previously discussed issue, please [link to it](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) here.
- [ X] Prefix your PR title with feat:, fix:, chore:, or docs:.
- [ X] This message body should clearly illustrate what problems it solves.
- [ X] Make sure the commit history is linear, up-to-date with main branch and does not contain any erroneous changes
- [ X] Format code with `pnpm format` and lint the project with `pnpm lint`
=>  fix:Make invoice success text larger #492 

apps/web/src/components/infoscreen/kanttiinit/index.tsx
Display maximum 5 food items in the kanttiinit view, pending the implementation of an autoscroller.
- ...
=> Hotfix: Remove overflow items from menu on infoscreen

apps/web/src/components/invoice-generator/index.tsx, apps/web/src/lib/api/external/laskugeneraattori/actions.ts, apps/web/src/lib/api/external/laskugeneraattori/index.ts, apps/web/src/locales/en.ts, apps/web/src/locales/fi.ts
Also removed cc-number category from account number autocomplete, so that browser actually remembers it
- ...
=> changed default item of invoice generator from product to receipt.

apps/web/src/app/[locale]/(main)/signups/[signupId]/[signupEditToken]/signup-form.tsx
=> feat: add back button to signup form

apps/web/src/lib/api/external/ilmomasiina/index.ts
=> fix: Add default value for ilmomasiina baseUrl

apps/web/src/app/[locale]/(main)/page.tsx, apps/web/src/components/april-fools/april-fools-alert.tsx
=> feat: Add april fools alert

apps/web/src/components/invoice-generator/index.tsx, apps/web/src/lib/api/external/laskugeneraattori/actions.ts, apps/web/src/lib/api/external/laskugeneraattori/index.ts
=> fix: remove unwanted date field from laskugeneraattori frontend

apps/cms/src/collections/committees/committees.ts, apps/web/src/components/committee-card/index.tsx, packages/cms-types/payload.ts, packages/cms-types/schema.gql
- **fix: typo while logging missing committee member**
- **fix(cms): disallow empty committee member**
- ...
=> fix: disallow empty committe member

apps/cms/src/payload.config.ts
=> Enable h4 in payload cms.

apps/web/src/globals/main-navigation.ts, flake.lock, flake.nix, packages/ui/tsup.config.ts
- **chore(nix): update nixpkgs and node**
- **fix: don't "use client" in ui**
- ...
=> fix: don't "use client" in ui

apps/web/src/app/[locale]/(main)/[...path]/page.tsx, apps/web/src/collections/pages.ts
- Title pretty much. Quick and dirty work with Codex
Linting seems to be broken somehow.
=> feat: add support for redirecting to external URLs

apps/web/next-env.d.ts, apps/web/src/components/lexical/lexical-serializer.tsx, apps/web/src/components/table-of-contents/index.tsx, apps/web/src/lib/utils.ts
Encountered this bug while doing other stuff, Claude was quick with fix.
Issue was that the ID of headings (and subheadings) did not take into account the possibility of 2 headings existing with same name.
=> fix: take duplicate header names into account

apps/web/next-env.d.ts, apps/web/src/blocks/collapsible.ts, apps/web/src/components/collapsible-block/index.tsx, apps/web/src/components/lexical/lexical-serializer.tsx, apps/web/src/components/lexical/types.ts, apps/web/src/payload.config.ts
Mikko asked for this, so I asked Claude to do it for me. I am creating value here.
=> feat: add a collapsbile component block
